#
# ABOUT
#
# Base Docker Compose file, defining services for:
# - django app
# - nginx front end
#
# USAGE
#
# symbolically link to this file from project root directory and then
# add environment-specific customization via an override file
#
# $ ln -s docker/docker-compose-base.yml docker-compose.yml
# $ ln -s docker/docker-compose-ops.override.yml docker-compose.override.yml
#

app:
  image: ncareol/python3-django-datavis:0.0.3
  volumes:
    - .:/app
  # command=/usr/local/bin/gunicorn -b 127.0.0.1:8000 -w 4 django_docker.wsgi --log-level=debug --log-file=/logs/gunicorn/gunicorn.log
  command: gunicorn -c datavis/settings/gunicorn.py --reload --workers 1 datavis.wsgi:application

web:
  image: nginx:alpine
  volumes:
    - .:/app
    - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  links:
    - app

